<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>x64</Platforms>
    <AssemblyName>MySSH</AssemblyName>
    <RootNamespace>MySSH</RootNamespace>
    <Version>0.1.0</Version>
    <AssemblyTitle>My SSH</AssemblyTitle>
    <Product>My SSH</Product>
    <Company>My SSH</Company>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
</Project>
